#     name: test-itest-deals_pricing
#     suite: itest-deals_pricing
#     target: "./itests/deals_pricing_test.go"
#
# - test:
#     name: test-itest-deals_publish
#     suite: itest-deals_publish
#     target: "./itests/deals_publish_test.go"
#
# - test:
#     name: test-itest-deals_retry_deal_no_funds
#     suite: itest-deals_retry_deal_no_funds
#     target: "./itests/deals_retry_deal_no_funds_test.go"
#
# - test:
#     name: test-itest-deals
#     suite: itest-deals
#     target: "./itests/deals_test.go"
#
# - test:
#     name: test-itest-gateway
#     suite: itest-gateway
#     target: "./itests/gateway_test.go"
#
# - test:
#     name: test-itest-get_messages_in_ts
#     suite: itest-get_messages_in_ts
#     target: "./itests/get_messages_in_ts_test.go"
#
# - test:
#     name: test-itest-multisig
#     suite: itest-multisig
#     target: "./itests/multisig_test.go"
#
# - test:
#     name: test-itest-nonce
#     suite: itest-nonce
#     target: "./itests/nonce_test.go"
#
# - test:
#     name: test-itest-paych_api
#     suite: itest-paych_api
#     target: "./itests/paych_api_test.go"
#
# - test:
#     name: test-itest-paych_cli
#     suite: itest-paych_cli
#     target: "./itests/paych_cli_test.go"
#
# - test:
#     name: test-itest-sdr_upgrade
#     suite: itest-sdr_upgrade
#     target: "./itests/sdr_upgrade_test.go"
#
# - test:
#     name: test-itest-sector_finalize_early
#     suite: itest-sector_finalize_early
#     target: "./itests/sector_finalize_early_test.go"
#
# - test:
#     name: test-itest-sector_miner_collateral
#     suite: itest-sector_miner_collateral
#     target: "./itests/sector_miner_collateral_test.go"
#
# - test:
#     name: test-itest-sector_pledge
#     suite: itest-sector_pledge
#     target: "./itests/sector_pledge_test.go"
#
# - test:
#     name: test-itest-sector_terminate
#     suite: itest-sector_terminate
#     target: "./itests/sector_terminate_test.go"
#
# - test:
#     name: test-itest-self_sent_txn
#     suite: itest-self_sent_txn
#     target: "./itests/self_sent_txn_test.go"
#
# - test:
#     name: test-itest-tape
#     suite: itest-tape
#     target: "./itests/tape_test.go"
#
# - test:
#     name: test-itest-verifreg
#     suite: itest-verifreg
#     target: "./itests/verifreg_test.go"
#
# - test:
#     name: test-itest-wdpost_dispute
#     suite: itest-wdpost_dispute
#     target: "./itests/wdpost_dispute_test.go"
#
# - test:
#     name: test-itest-wdpost
#     suite: itest-wdpost
#     target: "./itests/wdpost_test.go"
#
# - test:
#     name: test-unit-cli
#     suite: utest-unit-cli
#     target: "./cli/... ./cmd/... ./api/..."
# - test:
#     name: test-unit-node
#     suite: utest-unit-node
#     target: "./node/..."
# - test:
#     name: test-unit-rest
#     suite: utest-unit-rest
#     target: "./api/... ./blockstore/... ./build/... ./chain/... ./cli/... ./cmd/... ./conformance/... ./extern/... ./gateway/... ./journal/... ./lib/... ./markets/... ./node/... ./paychmgr/... ./storage/... ./tools/..."
# - test:
#     name: test-unit-storage
#     suite: utest-unit-storage
#     target: "./storage/... ./extern/..."
# - test:
#     go-test-flags: "-run=TestMulticoreSDR"
#     suite: multicore-sdr-check
#     target: "./extern/sector-storage/ffiwrapper"
#     proofs-log-test: "1"
# - test-conformance:
#     suite: conformance
#     codecov-upload: false
#     target: "./conformance"
# - test-conformance:
#     name: test-conformance-bleeding-edge
#     codecov-upload: false
#     suite: conformance-bleeding-edge
#     target: "./conformance"
#     vectors-branch: specs-actors-v7
# - trigger-testplans:
#     filters:
#       branches:
#         only:
#           - master
# - build-debug
- build-eudico
- build-all:
    filters:
      tags:
        only:
          - /^v\d+\.\d+\.\d+(-rc\d+)?$/
# - build-ntwk-calibration:
#     filters:
#       tags:
#         only:
#           - /^v\d+\.\d+\.\d+(-rc\d+)?$/
# - build-ntwk-butterfly:
#     filters:
#       tags:
#         only:
#           - /^v\d+\.\d+\.\d+(-rc\d+)?$/
# - build-lotus-soup
- build-macos:
    filters:
      tags:
        only:
          - /^v\d+\.\d+\.\d+(-rc\d+)?$/
- build-appimage:
    filters:
      branches:
        ignore:
          - /.*/
      tags:
        only:
          - /^v\d+\.\d+\.\d+(-rc\d+)?$/
# - publish:
#     requires:
#       - build-all
#       - build-macos
#     filters:
#       branches:
#         ignore:
#           - /.*/
#       tags:
#         only:
#           - /^v\d+\.\d+\.\d+(-rc\d+)?$/
# - build-and-push-image:
#     dockerfile: Dockerfile.lotus
#     path: .
#     repo: lotus-dev
#     tag: '${CIRCLE_SHA1:0:8}'
# - publish-packer-mainnet:
#     requires:
#       - build-all
#     filters:
#       branches:
#         ignore:
#           - /.*/
#       tags:
#         only:
#           - /^v\d+\.\d+\.\d+(-rc\d+)?$/
# - publish-packer-calibrationnet:
#     requires:
#       - build-ntwk-calibration
#     filters:
#       branches:
#         ignore:
#           - /.*/
#       tags:
#         only:
#           - /^v\d+\.\d+\.\d+(-rc\d+)?$/
# - publish-packer-butterflynet:
#     requires:
#       - build-ntwk-butterfly
#     filters:
#       branches:
#         ignore:
#           - /.*/
#       tags:
#         only:
#           - /^v\d+\.\d+\.\d+(-rc\d+)?$/
# - publish-snapcraft:
#     name: publish-snapcraft-stable
#     channel: stable
#     filters:
#       branches:
#         ignore:
#           - /.*/
#       tags:
#         only:
#           - /^v\d+\.\d+\.\d+(-rc\d+)?$/
# - publish-dockerhub:
#     name: publish-dockerhub
#     tag: stable
#     filters:
#       branches:
#         ignore:
#           - /.*/
#       tags:
#         only:
#           - /^v\d+\.\d+\.\d+(-rc\d+)?$/

# nightly:
#   triggers:
#     - schedule:
#         cron: "0 0 * * *"
#         filters:
#           branches:
#             only:
#               - master
#   jobs:
#     - publish-snapcraft:
#         name: publish-snapcraft-nightly
#         channel: edge
#     - publish-dockerhub:
#         name: publish-dockerhub-nightly
#         tag: nightlyer-snap