name: itests
on:
  push:
    branches:
      - spacenet
  pull_request:

jobs:
  itests-go-stable:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        go: [ '1.18' ]
    timeout-minutes: 10
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: InstallDependencies
        run: sudo apt-get update && sudo apt-get install mesa-opencl-icd ocl-icd-opencl-dev gcc git bzr jq pkg-config curl clang build-essential hwloc libhwloc-dev wget -y && sudo apt-get upgrade -y

      - name: CashGoModules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: make spacenet
