name: NighltyTest
# This workflow runs long nightly integration tests with Mir's mangler.
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        go: [ '1.18' ]
    timeout-minutes: 60
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: InstallDependencies
        run: sudo apt-get update && sudo apt-get install -y mesa-opencl-icd ocl-icd-opencl-dev gcc git bzr jq pkg-config curl clang build-essential hwloc libhwloc-dev wget

      - name: CashGoModules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: RestoreFilecoinProofData
        id: cache-filecoin-data-restore
        uses: actions/cache/restore@v3
        with:
          path: /var/tmp/filecoin-proof-parameters/
          key: ${{ runner.os }}-filecoinparams

      - name: Deps
        run: make deps

      - name: Tests with mangler
        run: make spacenet-mangling-test

      - name: SaveFilecoinProofData
        id: cache-filecoin-data-save
        uses: actions/cache/save@v3
        with:
          path: /var/tmp/filecoin-proof-parameters/
          key: ${{ steps.cache-filecoin-data-restore.outputs.cache-primary-key }}
